#if !canImport(ObjectiveC)
import XCTest

extension AbsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AbsTests = [
        ("testInt", testInt),
        ("testFloat", testFloat),
        ("testDouble", testDouble),
    ]
}

extension AffineTransformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AffineTransformationTests = [
        ("testAffineTransform", testAffineTransform),
    ]
}

extension BayerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BayerTests = [
        ("testBayered", testBayered),
        ("testDebayered", testDebayered),
    ]
}

extension BicubicInterpolationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BicubicInterpolationTests = [
        ("testInterpolate", testInterpolate),
    ]
}

extension BilinearInterpolationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BilinearInterpolationTests = [
        ("testInterpolate", testInterpolate),
    ]
}

extension BitOperationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BitOperationsTests = [
        ("testNegate", testNegate),
        ("testAnd", testAnd),
        ("testOr", testOr),
        ("testXor", testXor),
    ]
}

extension ChannelCompositionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChannelCompositionTests = [
        ("testCompound", testCompound),
    ]
}

extension ChannelSubscriptTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChannelSubscriptTests = [
        ("testChannelSubscriptGet", testChannelSubscriptGet),
        ("testChannelSubscriptSet", testChannelSubscriptSet),
    ]
}

extension ChannelwiseConversionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChannelwiseConversionTests = [
        ("testChannelwiseConvert", testChannelwiseConvert),
        ("testConvertChannel", testConvertChannel),
        ("testConvertRange", testConvertRange),
    ]
}

extension CheckBoolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CheckBoolTests = [
        ("testHasTrue", testHasTrue),
        ("testHasFalse", testHasFalse),
        ("testAllTrue", testAllTrue),
        ("testAllFalse", testAllFalse),
    ]
}

extension ClampTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClampTests = [
        ("testClamp", testClamp),
    ]
}

extension ClipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClipTests = [
        ("testClip", testClip),
    ]
}

extension ColorArithmeticTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ColorArithmeticTests = [
        ("testNegate", testNegate),
        ("testAddInt", testAddInt),
        ("testAddDouble", testAddDouble),
        ("testSubInt", testSubInt),
        ("testSubDouble", testSubDouble),
        ("testMulInt", testMulInt),
        ("testMulDouble", testMulDouble),
        ("testDivInt", testDivInt),
        ("testDivDouble", testDivDouble),
    ]
}

extension ConvolutionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConvolutionTests = [
        ("testGaussianFilter", testGaussianFilter),
        ("testConvoluted", testConvoluted),
    ]
}

extension CorrelationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CorrelationTests = [
        ("testSSD", testSSD),
        ("testSAD", testSAD),
        ("testNCC", testNCC),
        ("testZNCC", testZNCC),
        ("testScale", testScale),
    ]
}

extension DataTypeConversionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataTypeConversionTests = [
        ("testCast", testCast),
        ("testRounding", testRounding),
    ]
}

extension DrawTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DrawTests = [
        ("testDrawRect", testDrawRect),
        ("testDrawRectPelimeter", testDrawRectPelimeter),
        ("testDrawImage", testDrawImage),
        ("testDrawText", testDrawText),
    ]
}

extension EdgeModeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EdgeModeTests = [
        ("testConstant", testConstant),
        ("testEdge", testEdge),
        ("testWrap", testWrap),
        ("testSymmetric", testSymmetric),
        ("testReflect", testReflect),
    ]
}

extension ExtremaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtremaTests = [
        ("testExtrema", testExtrema),
    ]
}

extension FilterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FilterTests = [
        ("testMaximumFilter", testMaximumFilter),
        ("testMinimumFilter", testMinimumFilter),
        ("testMedianFilter", testMedianFilter),
    ]
}

extension Im2colTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Im2colTests = [
        ("testIm2Col", testIm2Col),
        ("testIm2Row", testIm2Row),
    ]
}

extension ImageArithmeticTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageArithmeticTests = [
        ("testNegate", testNegate),
        ("testAddInt", testAddInt),
        ("testAddDouble", testAddDouble),
        ("testSubInt", testSubInt),
        ("testSubDouble", testSubDouble),
        ("testMulInt", testMulInt),
        ("testMulDouble", testMulDouble),
        ("testDivInt", testDivInt),
        ("testDivDouble", testDivDouble),
    ]
}

extension ImageIOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageIOTests = [
        ("testSaveLoadUInt8", testSaveLoadUInt8),
        ("testSaveLoadFloat", testSaveLoadFloat),
        ("testSaveLoadDouble", testSaveLoadDouble),
    ]
}

extension ImageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageTests = [
        ("testInitialize", testInitialize),
        ("testEquality", testEquality),
        ("testCoW", testCoW),
    ]
}

extension IntegralImageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntegralImageTests = [
        ("testToIntegralImage", testToIntegralImage),
    ]
}

extension LikeInitializerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LikeInitializerTests = [
        ("testLike", testLike),
    ]
}

extension NearestNeighborInterpolatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NearestNeighborInterpolatorTests = [
        ("testInterpolate", testInterpolate),
    ]
}

extension PaddingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PaddingTests = [
        ("testConstantPadding", testConstantPadding),
        ("testSymmetricPadding", testSymmetricPadding),
        ("testZeroPadding", testZeroPadding),
    ]
}

extension PixelIteratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PixelIteratorTests = [
        ("testIterator", testIterator),
        ("testIteratorRange", testIteratorRange),
    ]
}

extension PixelRefArithmeticTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PixelRefArithmeticTests = [
        ("testAdd", testAdd),
        ("testSub", testSub),
        ("testMul", testMul),
        ("testDiv", testDiv),
    ]
}

extension PixelSubscriptTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PixelSubscriptTests = [
        ("testSubscriptGet", testSubscriptGet),
        ("testSubscriptSet", testSubscriptSet),
    ]
}

extension PixelTypeConversionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PixelTypeConversionTests = [
        ("testToGray", testToGray),
        ("testGrayToGrayAlpha", testGrayToGrayAlpha),
        ("testGrayToRGB", testGrayToRGB),
        ("testGrayToRGBA", testGrayToRGBA),
        ("testRGBtoRGBA", testRGBtoRGBA),
        ("testRGBAtoRGB", testRGBAtoRGB),
        ("testARGBtoRGBA", testARGBtoRGBA),
        ("testRGBAtoARGB", testRGBAtoARGB),
    ]
}

extension PixelwiseConversion {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PixelwiseConversion = [
        ("testConvert", testConvert),
        ("testConvertRange", testConvertRange),
        ("testConverted", testConverted),
    ]
}

extension PowerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PowerTests = [
        ("testPowFloat", testPowFloat),
        ("testPowDouble", testPowDouble),
    ]
}

extension ProjectiveTransformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProjectiveTransformationTests = [
        ("testProjectiveTransformation", testProjectiveTransformation),
    ]
}

extension ResizeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResizeTests = [
        ("testResizeNN_UInt8", testResizeNN_UInt8),
        ("testResizeAA_upscale", testResizeAA_upscale),
        ("testResizeAA_downscale_separate", testResizeAA_downscale_separate),
        ("testResizeAA_downscale", testResizeAA_downscale),
        ("testResizeAA_separate", testResizeAA_separate),
    ]
}

extension RoundingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RoundingTests = [
        ("testRound", testRound),
        ("testCeil", testCeil),
        ("testFloor", testFloor),
        ("testTrunc", testTrunc),
    ]
}

extension SubimageSubscriptTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubimageSubscriptTests = [
        ("testSubimageSubscriptGet", testSubimageSubscriptGet),
        ("testSubimageSubscriptSet", testSubimageSubscriptSet),
    ]
}

extension TransformationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransformationTests = [
        ("testFlipLR", testFlipLR),
        ("testFlipUD", testFlipUD),
        ("testRot", testRot),
        ("testFlipLR", testFlipLR),
        ("testFlipUD", testFlipUD),
        ("testRot", testRot),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BayerTests.__allTests__BayerTests),
        testCase(CorrelationTests.__allTests__CorrelationTests),
        testCase(Im2colTests.__allTests__Im2colTests),
        testCase(IntegralImageTests.__allTests__IntegralImageTests),
        testCase(ImageArithmeticTests.__allTests__ImageArithmeticTests),
        testCase(PixelRefArithmeticTests.__allTests__PixelRefArithmeticTests),
        testCase(ColorArithmeticTests.__allTests__ColorArithmeticTests),
        testCase(BitOperationsTests.__allTests__BitOperationsTests),
        testCase(CheckBoolTests.__allTests__CheckBoolTests),
        testCase(ChannelCompositionTests.__allTests__ChannelCompositionTests),
        testCase(ChannelwiseConversionTests.__allTests__ChannelwiseConversionTests),
        testCase(DataTypeConversionTests.__allTests__DataTypeConversionTests),
        testCase(PixelTypeConversionTests.__allTests__PixelTypeConversionTests),
        testCase(PixelwiseConversion.__allTests__PixelwiseConversion),
        testCase(ImageTests.__allTests__ImageTests),
        testCase(LikeInitializerTests.__allTests__LikeInitializerTests),
        testCase(PixelIteratorTests.__allTests__PixelIteratorTests),
        testCase(DrawTests.__allTests__DrawTests),
        testCase(ConvolutionTests.__allTests__ConvolutionTests),
        testCase(FilterTests.__allTests__FilterTests),
        testCase(ImageIOTests.__allTests__ImageIOTests),
        testCase(BicubicInterpolationTests.__allTests__BicubicInterpolationTests),
        testCase(BilinearInterpolationTests.__allTests__BilinearInterpolationTests),
        testCase(NearestNeighborInterpolatorTests.__allTests__NearestNeighborInterpolatorTests),
        testCase(AbsTests.__allTests__AbsTests),
        testCase(ClipTests.__allTests__ClipTests),
        testCase(PowerTests.__allTests__PowerTests),
        testCase(RoundingTests.__allTests__RoundingTests),
        testCase(ExtremaTests.__allTests__ExtremaTests),
        testCase(ChannelSubscriptTests.__allTests__ChannelSubscriptTests),
        testCase(PixelSubscriptTests.__allTests__PixelSubscriptTests),
        testCase(SubimageSubscriptTests.__allTests__SubimageSubscriptTests),
        testCase(AffineTransformationTests.__allTests__AffineTransformationTests),
        testCase(EdgeModeTests.__allTests__EdgeModeTests),
        testCase(PaddingTests.__allTests__PaddingTests),
        testCase(ProjectiveTransformationTests.__allTests__ProjectiveTransformationTests),
        testCase(ResizeTests.__allTests__ResizeTests),
        testCase(TransformationTests.__allTests__TransformationTests),
        testCase(ClampTests.__allTests__ClampTests),
    ]
}
#endif
